### ISSUE TITLE
Does it work on wii?

### ISSUE THREAD

**Issue by Alexyo21** [Aurelio92/RVLoader#13]
Hi, I tried to install it on first gen wii, with GameCube retro compatibility(EUR), but when I boot the installer from homebrew channel, however it crashes and displays an error, all the times.
I put all the files on sd card because from usb stick they didn't display on homebrew channel. I was forgetting, My wii is full "hacked".

**Comment by Aurelio92** [comment]
It only works from USB drives, not SD cards. Copy all the files on the USB drive and remove the SD card from your Wii. It will show up in the homebrew channel
