### ISSUE TITLE
Question. Wii U supported or no. vWii compataible?

### ISSUE THREAD

**Issue by briantho** [Aurelio92/RVLoader#15]
Title pretty much says it all. Is this compatible with vWii (Wii U) or not. 
I found nothing in the FAQ, so please let me know if this is safe or not to install on the Wii U. In other words can this be run on wii mode on the wii u???

**Comment by Carter1190** [comment]
judging by vwii using different ios and such,no this wont work on vwii,

**Comment by briantho** [comment]
understandable. Is there any plan to support the wii u?

**Comment by Aurelio92** [comment]
Not really, not currently
