### ISSUE TITLE
error could not open theme file

### ISSUE THREAD

**Issue by rebornshadow134** [Aurelio92/RVLoader#24]
I could have just missed something but i keep getting " error could not open theme file. dose anyone have a solution to this?

**Comment by Aurelio92** [comment]
When that happens it could mean either an incompatible USB drive or a badly formatted one. Make sure to format it in FAT32 with 32kB cluster size using http://ridgecrop.co.uk/index.htm?guiformat.htm
Also unplug any SD card from your Wii if you have one
