### ISSUE TITLE
Tatsunoko VS capcom  WII black screen (all versions JAP US EU)

### ISSUE THREAD

**Issue by Freeman2006** [Aurelio92/RVLoader#69]
**Please complete the following information:**
 - RVLoader Version: [e.g. 1.6]
 - Wii Revision: [e.g. RVL-CPU-40 (USA)]
 - Trimmed: [e.g. Yes, OMGWTF]
 - Relocations: [e.g. Bluetooth, Wifi, MX]
 - (Micro)SD / USB Model: [e.g. 128GB SanDisk MicroSD (SDSQXAO-128G-GNCZN)]

**Describe the bug**

**To Reproduce**
2. Select '....'
3. Exit to '....'

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by Freeman2006** [comment]
tested with RVloader 1.6

**Comment by Aurelio92** [comment]
For some odd reason, if you have any GC controller/memcard plugged in, the game fails to boot. I will try to patch the game somehow

**Comment by Aurelio92** [comment]
Will be fixed in next release
