### ISSUE TITLE
[BUG REPORT] Background Images Have a Grey Bar on Right Side in 16:9

### ISSUE THREAD

**Issue by Bryceshaw06** [Aurelio92/RVLoader#70]
**Please complete the following information:**
 - RVLoader Version: [1.7 Beta]
 - Wii Revision: [RVL-CPU-40 (USA)]
 - Trimmed: [Yes, OMGWTF]
 - Relocations: [Bluetooth]
 - (Micro)SD / USB Model: [128GB SanDisk MicroSD (SDSQXAO-128G-GNCZN)]

**Describe the bug**
Background images have a grey bar on the right side of the RVLoader menu whe the Wii is in 16:9 mode

**To Reproduce**
1. Go to settings - loader
2. Change the background image to anything but "grey.png"
3. Save changes

**Expected behavior**
No black bar

**Screenshots**
![IMG_6163](https://github.com/Aurelio92/RVLoader/assets/88813136/d9d0acbd-e20b-4159-9755-a7587473fe57)

**Comment by Aurelio92** [comment]
This is a known issue and was fixed in commit 16da127
