### ISSUE TITLE
[BUG REPORT] Metal Slug Anthology Wii has no video but have sound

### ISSUE THREAD

**Issue by jetcodisc** [Aurelio92/RVLoader#74]
**Please complete the following information:**
 - RVLoader Version: 1.6
 - Wii Revision: RVL-CPU-40 (USA)
 - Trimmed: Yes, OMGWTF and OMEGA
 - Relocations: Bluetooth, Wifi, MX
 - (Micro)SD / USB Model: 128GB SanDisk MicroSD (SDSQXAO-128G-GNCZN)

**Describe the bug**
When started the game on a gboy, it shows blue screen "No Signal" then red screen "Not Support". I can hear the sound though after a waiting for it to load, and the game can even sense my button presses. Just no video.

**Comment by Aurelio92** [comment]
Is this with VGA? Sounds to me like your screen does not support interlaced video

**Comment by jetcodisc** [comment]
Yes this is with VGA. I always thought it doesn't work with rvloader, but I just tried with HDMI and it worked! Thanks for the quick reply.
