### ISSUE TITLE
Is it possible to install this on a Wii who already doesnt have a bluetooth sensor

### ISSUE THREAD

**Issue by GOTHMONEY** [Aurelio92/RVLoader#86]
One of my Wiis' bluetooth sensor died and nothing renders on my monitor is this possible to install this regardless in order to have the Wii start working again or is it just croaked until my bluetooth sensor arrives int he mail

**Comment by Bryceshaw06** [comment]
No, RVLoader can patch out the need for a Bluetooth module, but still needs Bluetooth and Wi-Fi for initial setup. Please close this issue
